
name: Build test ROMs
run-name: Generate tests and build ROMs

on: [push]

jobs:
  generate-roms:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install gcc-arm-none-eabi pypy3
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
      - name: Build GBA ROMs
        run: make -C gba
      - name: Package assets
        run: zip -r gba-test-roms.zip $( find -name "*.gba" )
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: gba-test-roms-${{ steps.slug.outputs.sha8 }}
          path: gba-test-roms.zip

